- job:
    name: testjob
    run: playbooks/testjob.yaml

- project:
    check:
      jobs:
        - testjob
        
- project:
    check:
      jobs:
        - noop
        
- job:
    name: unittests
    parent: base
    pre-run: playbooks/testjob.yaml
    
    
- project:
    check:
      jobs:
        - testjob
