- hosts: 1ebd8c6bb801.ngrok.io
  tasks:
    - name: This is a test task
      debug:
        msg: You should see me in the logs.
    - debug: var=ansible_date_time
    - debug: msg="the current date is {{ ansible_date_time.date }}"
    - name: Another test task
      command: pwd
